Repository spdx/meetings, pull requests merged in 2024-01, with the labels that each got.

#596 Dec General Meeting minutes
  general/2023-12-07.md
Labels: General

#591 Create 2023-12-19.md
  tech/2023-12-19.md
Labels: Tech

#582 Create 2023-11-27.md
  asia/SPDX Asia Tech Team Meeting 2023-11-27.md
Labels: Asia

#557 Create 2023-10-18.md
  ai/SPDX AI Team Meeting 2023-10-18.md
Labels: AI

#558 Create 2023-10-25.md
  ai/SPDX AI Team Meeting 2023-10-25.md
Labels: AI

#573 Create 2023-11-01.md
  ai/SPDX AI Team Meeting 2023-11-01.md
Labels: AI

#549 Create 2023-02-22.md
  ai/SPDX AI Team Minutes 2023-02-22.md
Labels: AI

#548 Create 2023-01-25.md
  ai/SPDX AI Team Minutes 2023-01-25.md
Labels: AI

#547 Create 2023-01-18.md
  ai/SPDX AI Team Minutes 2023-01-18.md
Labels: AI

#546 Create 2023-01-11.md
  ai/SPDX AI team minutes 2023-01-11.md
Labels: AI

#543 Create 2022-11-02.md
  ai/SPDX AI team minutes 2022-11-02.md
Labels: AI

#542 Create 2022-10-26.md
  ai/SPDX AI team minutes 2022-10-26.md
Labels: AI

#541 Create 2022-10-19.md
  ai/SPDX AI Team Minutes 2022-10-19.md
Labels: AI

#540 Create 2022-08-31.md
  ai/SPDX AI team minutes 2022-08-31.md
Labels: AI

#539 Create 2022-08-24.md
  ai/SPDX AI team minutes 2022-08-24.md
Labels: AI

#538 Create 2022-08-17.md
  ai/SPDX AI team minutes, 2022-08-17.md
Labels: AI

#536 Create 2023-03-01.md
  ai/SPDX AI Team Minutes 2023-03-01.md
Labels: AI

#535 Create 2022-08-10.md
  ai/SPDX AI team minutes, 2022-08-10.md
Labels: AI

#534 Create 2023-08-03.md
  ai/SPDX AI team minutes 2023-08-03.md
Labels: AI

#533 Create 2023-03-29.md
  ai/SPDX AI Team Minutes 2023-03-29.md
Labels: AI

#532 Create 2023-04-05.md
  ai/SPDX AI team minutes 2023-04-05.md
Labels: AI

#531 Create 2023-05-03.md
  ai/SPDX AI Team Minutes 2023-05-03.md
Labels: AI

#529 Create 2023-05-24.md
  ai/SPDX AI Team Minutes 2023-05-24.md
Labels: AI

#526 Create 2023-08-16.md
  ai/SPDX AI Team Meeting 2023-08-16.md
Labels: AI

#525 Create 2023-08-23.md
  ai/SPDX AI Team Meeting 2023-08-23.md
Labels: AI

#524 Create 2023-08-30.md
  ai/SPDX AI Team Meeting 2023-08-30.md
Labels: AI

#523 Create 2023-09-06.md
  ai/SPDX AI Team Meeting 2023-09-06.md
Labels: AI

#522 Create 2023-09-13.md
  ai/SPDX AI Team Meeting 2023-09-13.md
Labels: AI

#521 Create 2023-09-27.md
  ai/SPDX AI Team Meeting 2023-09-27.md
Labels: AI

#412 Create 2022-07-27.md
  ai/SPDX AI team minutes, July 27, 2022.md
Labels: AI

#410 Create 2022-07-31.md
  ai/SPDX AI team minutes, July 13, 2022.md
Labels: AI

#409 Create 2023-05-31.md
  ai/SPDX AI Team Minutes, May 31, 2023.md
Labels: AI

#408 Create 2023-06-07.md
  ai/SPDX AI Team Minutes, June 7, 2023.md
Labels: AI

#407 Create 2023-06-21.md
  ai/SPDX AI Team Minutes, June 21, 2023.md
Labels: AI

#406 Create 2023-06-28.md
  ai/SPDX AI Team Minutes, June 28, 2023.md
Labels: AI

#405 Create 2023-07-05.md
  ai/SPDX AI Team Minutes, July 5, 2023.md
Labels: AI

#403 Create 2023-07-19.md
  ai/SPDX AI Team Minutes, July 19, 2023.md
Labels: AI

#402 Create 2023-07-26.md
  ai/SPDX AI Team Minutes, July 26, 2023.md
Labels: AI

#401 Create 2023-08-02.md
  ai/SPDX AI Team Minutes,  August 2, 2023.md
Labels: AI

#574 Create 2023-11-08.md
  ai/SPDX AI Team Meeting 2023-11-08.md
Labels: AI

#600 Create 2024-01-29.md
  service/2024-01-29.md
Labels: Service
