Repository spdx/meetings, pull requests merged in 2024-07, with the labels that each got.

#561 Add legal team working session minutes for 2023-09-08
  legal/2023-09-08.md
Labels: Legal

#562 Add legal team minutes for 2023-09-14
  legal/2023-09-14.md
Labels: Legal

#713 Add June General Meeting minutes
  general/2024/2024-06-06.md
Labels: General

#740 Create 2024-07-09.md
  tech/2024-07-09.md
Labels: Tech

#581 Create 2023-11-23.md
  ai/SPDX AI Team Meeting 2023-11-23.md
Labels: AI

#748 Create 2024-07-23.md
  tech/2024/2024-07-23.md
Labels: Tech

#729 Create 2024-07-02.md
  tech/2024-07-02.md
Labels: Tech

#745 Create 2024-07-16.md
  tech/2024/2024-07-16.md
Labels: Tech

#751 Create 2024-07-30.md
  tech/2024/2024-07-30.md
Labels: Tech

#749 Create 2024-07-24.md
  ai/2024/2024-07-24.md
Labels: AI

#746 Create 2024-07-17.md
  ai/2024/2024-07-17.md
Labels: AI

#730 Create 2024-07-03.md
  ai/2024-07-03.md
Labels: AI

#725 Create 2024-06-26.md
  ai/2024-06-26.md
Labels: AI

#664 Create 2024-04-10.md
  ai/2024-04-10.md
Labels: AI

#702 Add AI minutes 2024-05-22
  ai/2024/2024-05-22.md
Labels: AI

#712 Add AI minutes 2024-05-29
  ai/2024/2024-05-29.md
Labels: AI

#411 Create 2022-07-20.md
  ai/SPDX AI team minutes, July 20, 2022.md
Labels: AI
